### ISSUE TITLE
NullPointerExceptions

### ISSUE THREAD

**Issue by cessnageek** [Team-9968/FTC_2016#1]
So in the master branch there are some null pointer exceptions that happen when the unexpected happens.  This will need to be fixed.  Right now it works, but if a robot runs into something, no guarantees.

**Comment by dawsonjeffreyd** [comment]
If the "unexpected doesn't happen" doesn't that mean it was expected ;)

-Jeff

-Jeff

**Comment by cessnageek** [comment]
True :)  You get the point

**Comment by dawsonjeffreyd** [comment]
Is this issue ready to close?  I'm not sure if it was resolved.  If not, can you reproduce and show me the problem?

**Comment by cessnageek** [comment]
Eh yeah you can gouse it. I get them sometimes but I'm not sure it's my code
